name: Deployment Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Deploy-Docker-Infra:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on remote server
        uses: appleboy/ssh-action@v1.2.0

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

          # Traefik  test
          TRAEFIK_TRAEFIK_PORT_1: ${{ secrets.TRAEFIK_TRAEFIK_PORT_1 }}
          TRAEFIK_TRAEFIK_PORT_2: ${{ secrets.TRAEFIK_TRAEFIK_PORT_2 }}
          TRAEFIK_SERVER_PORT: ${{ secrets.TRAEFIK_SERVER_PORT }}
          TRAEFIK_TRAEFIK_DOMAIN: ${{ secrets.TRAEFIK_TRAEFIK_DOMAIN }}
          TRAEFIK_TRAEFIK_MIDDLEWARE: ${{ secrets.TRAEFIK_TRAEFIK_MIDDLEWARE }}
          TRAEFIK_URL: ${{ secrets.TRAEFIK_URL }}
          TRAEFIK_USER: ${{ secrets.TRAEFIK_USER }}
          TRAEFIK_ID: ${{ secrets.TRAEFIK_ID }}
          TRAEFIK_SECRET: ${{ secrets.TRAEFIK_SECRET }}
          TRAEFIK_WHITELIST: ${{ secrets.TRAEFIK_WHITELIST }}
          TRAEFIK_TINYAUTH_URL: ${{ secrets.TRAEFIK_TINYAUTH_URL }}
          TRAEFIK_FORWARD_ADRESS: ${{ secrets.TRAEFIK_FORWARD_ADRESS }}
          
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          envs: GH_TOKEN,FAIL2BAN_FAIL2BAN_UI_DOMAIN,FAIL2BAN_FAIL2BAN_UI_PORT,FAIL2BAN_TRAEFIK_MIDDLEWARE,FAIL2BAN_ENTRYPOINTS,FAIL2BAN_TLS,MONITORING_UPTIME_PUBLIC_HOST,MONITORING_UPTIME_PRIVATE_HOST,MONITORING_UPTIME_PORT,MONITORING_TRAEFIK_MIDDLEWARE,TASKLIST_TASKLIST_DOMAIN,TASKLIST_FRONTEND_PORT,TASKLIST_BACKEND_PORT,TASKLIST_TRAEFIK_MIDDLEWARE,TASKLIST_DB_HOST,TASKLIST_DB_PORT,TASKLIST_DB_USER,TASKLIST_DB_PASSWORD,TASKLIST_DB_NAME,TASKLIST_MARIADB_ROOT_PASSWORD,TRAEFIK_TRAEFIK_PORT_1,TRAEFIK_TRAEFIK_PORT_2,TRAEFIK_SERVER_PORT,TRAEFIK_TRAEFIK_DOMAIN,TRAEFIK_TRAEFIK_MIDDLEWARE,TRAEFIK_URL,TRAEFIK_USER,TRAEFIK_ID,TRAEFIK_SECRET,TRAEFIK_WHITELIST,TRAEFIK_TINYAUTH_URL,TRAEFIK_FORWARD_ADRESS,WIKI_URL_WIKI,WIKI_PORT

          script: |
            # clone le rep
            git clone https://$GH_TOKEN@github.com/EmilienRoche/Serveur-Internet-Sample-Project.git
            
            # copie vers /root/srv
            rsync -av Serveur-Internet-Sample-Project/home/rocky/srv/tasklist/ /home/rocky/srv/


            # suppression du repo cloné
            rm -rf Serveur-Internet-Sample-Project

            # Traefik
            cd /home/rocky/srv/traefik
            cat <<'EOF' > .env
            TRAEFIK_PORT_1=$TRAEFIK_TRAEFIK_PORT_1
            TRAEFIK_PORT_2=$TRAEFIK_TRAEFIK_PORT_2
            SERVER_PORT=$TRAEFIK_SERVER_PORT
            TRAEFIK_DOMAIN=$TRAEFIK_TRAEFIK_DOMAIN
            TRAEFIK_MIDDLEWARE=$TRAEFIK_TRAEFIK_MIDDLEWARE
            URL=$TRAEFIK_URL
            USERS=$TRAEFIK_USER
            ID=$TRAEFIK_ID
            SECRET=$TRAEFIK_SECRET
            TINYAUTH_URL=$TRAEFIK_TINYAUTH_URL
            FORWARD_ADRESS=$TRAEFIK_FORWARD_ADRESS
            EOF

            # lancement docker
            cd /home/rocky/srv/traefik
            docker compose up -d --force-recreate
